<?
$values=$_COOKIE[user];
require "header.php";
echo "</li>\n";
echo "</ul>\n";
echo "</div>\n";
echo "<div id=\"bar\">\n";
echo "<div id=\"show_goods\">\n";
echo "<h2>\n";
echo "<a href=\"#\">查看所有分类</a>\n";
echo "</h2>\n";
echo "</div>\n";
echo "<div id=\"show_ul\">\n";
echo "<ul class=\"bar\">\n";
echo "<li id=\"li_1\">\n";
echo "<a href=\"HomePage.php\">首页</a>\n";
echo "</li>\n";
echo "<li>\n";
echo "<a href=\"#\">社区</a>\n";
echo "</li>\n";
echo "</ul>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div id=\"all_sort\">\n";
echo "<div id=\"item_1\">\n";
echo "<a href=\"#\">图书</a>\n";
echo "<s></s>\n";
echo "</div>\n";
echo "<div id=\"item_2\">\n";
echo "<a href=\"#\">电子商品</a>\n";
echo "<s></s>\n";
echo "</div>\n";
echo "<div id=\"item_3\">\n";
echo "<a href=\"#\">生活</a>\n";
echo "<s></s>\n";
echo "</div>\n";
echo "<div id=\"item_4\">\n";
echo "<a href=\"#\">其他</a>\n";
echo "<s></s>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div id=\"good_1\">\n";
echo "<dl class=\"book_1\">\n";
echo "<dt>\n";
echo "<a href=\"scanByType.php\">计算机教材</a>\n";
echo "</dt>\n";	
echo "<dt>\n";
echo "<a href=\"#\">参考书</a>\n";
echo "</dt>\n";
echo "</dl>\n";
echo "</div>\n";
echo "<div id=\"good_2\">\n";
echo "<div></div>";
echo "</div>\n";
echo "<div id=\"good_3\">\n";
echo "<div></div>";
echo "</div>\n";
echo "<div id=\"good_4\">\n";
echo "<div></div>";
echo "</div>\n";
echo "<div id=\"goods\">\n";
echo "<div id=\"show_new\"></div>\n";
echo "<div id=\"nav\">\n";
echo "<span>1</span>\n";
echo "<span>2</span>\n";
echo "<span>3</span>\n";
echo "<span>4</span>\n";
echo "<span>5</span>\n";
echo "</div>\n";
echo "</div>\n";
?>
